#!/usr/bin/env bash
# This script is displaying numbers from 1 to 100 in a list, displaying FizzBuzz when the number is a multiple of 3 and 5, Fizz when the number is a multiple of 3 and Buzz when the number is a multiple of 5

i=1

while [ $i -le 100 ]
do
	if ((i%3 == 0)) && ((i%5 == 0));
	then
		echo "FizzBuzz";

	elif ((i%3 == 0));
	then
		echo "Fizz";

	elif ((i%5 == 0));
	then
		echo "Buzz"
	else
		echo $i
	fi

	((i++))
done

