#!/usr/bin/env bash
# This script is displaying the content of the file /etc/passwd: username, user id and home directory path for the user

i=1

while [ $i -lt 2 ]
do
	cat /etc/passwd | cut -d ":" -f 1,3,6
done
