#!/usr/bin/env bash
# This script is displaying loops from 1 to 10: bad luck, good luck and Best School

counter=1

while [ $counter -le 10 ]
do
	if ((counter==4));
	then
		echo "bad luck";
	elif ((counter==8))
	then
		echo "good luck";
	else
	echo "Best School";
	fi
	((counter++))
done
