#!/usr/bin/env bash
# This script is displaying the time for 12 hours and 59 minutes: hours from 0 to 12, and minutes from 1 to 59

h=0
m=1

echo "Hour: $((h))"

while [ $h -le 12 ]
do
	while [ $m -le 59 ]
		do
			echo $m
			((m++))
		done
 
	((h++))
	echo "Hour: $((h))";
	m=1
done
