#!/usr/bin/env bash
# This script is displaying the content of the current directory in a list format. Only the first part of the name is displaying

ls > list

for _ in 'list';
do
	cat list;
	cut -d "/" -f 2;
	tr "	" "\n";
done
