#!/usr/bin/env bash
# This script is displaying the content of the current directory in a list format. Only the first part of the name is displaying

i=1

for _ in $i;
do
	find . -name "[!.]*" | cut -d "/" -f 2 | cut -d "-" -f 2;
done
