#!/usr/bin/env bash
# This script is displaying your information about the school file

if [ -a school ]
then
	echo "school file exists"

	if [ -s school ]
	then 
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

else
	echo "school file does not exist"
fi

if [ -f school ]
then
	echo "school is a regular file"
fi


