#!/usr/bin/env bash
# This script:

# Creates the file /var/run/myscript.pid containing its PID
touch /var/run/myscript.pid ; echo $$ > /var/run/myscript.pid

# Displays I hate the kill command when receiving a SIGTERM signal
trap "echo I hate the kill command; rm /var/run/myscript.pid; pkill -9 -f '10-process_and_pid_file' " SIGTERM 

# Displays Y U no love me?! when receiving a SIGINT signal
trap "echo Y U no love me?" SIGINT


# Displays To infinity and beyond indefinitely
i=10

while ((i>1))
do
	echo "To infinity and beyond"
	sleep 2
done

# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal


